# throttle
axis_linear: 1
scale_linear: 1.0
scale_linear_turbo: 1.5

# steering
axis_angular: 3
scale_angular: -1.0

# deadman button
enable_button: 4  # LB shoulder button (Logitech)
enable_turbo_button: 10  # L1 shoulder button
