local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 1.0

  publish_voxel_map: true
  static_map: true

  map_type: voxel
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  unknown_threshold: 10
  mark_threshold: 0

  transform_tolerance: 0.3
  obstacle_range: 2.5
  max_obstacle_height: 2.0
  raytrace_range: 3.0
  footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
  footprint_padding: 0.01
  inflation_radius: 0.55
  cost_scaling_factor: 10.0
  lethal_cost_threshold: 100

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    enabled: true
    observation_sources: point_cloud_sensor
    point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /oak/points, marking: true, clearing: true}

  inflation_layer:
    enabled: true
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
